<?php
/**
 * HourlyAssetSeries
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SkyWise Insight API (Beta)
 *
 * The SkyWise Insight API is an interface to WDT’s Weather as a Service® analytics platform,  allowing application developers to leverage high quality weather information  for applications, and products. The SkyWise Insight API provides access to  historical, current, and forecast data for any region of interest,  such as an agriculture field, urban area, or utility service area.  API response formats can include time-series, summaries, or contours.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * HourlyAssetSeries Class Doc Comment
 *
 * @category    Class
 * @description Series list
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HourlyAssetSeries implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'HourlyAssetSeries';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'valid_time' => 'string',
        'value' => 'double',
        'contours' => 'string',
        'asset_statistics' => '\Swagger\Client\Model\DailyAssetSeriesAssetStatistics',
        'products' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'valid_time' => null,
        'value' => 'double',
        'contours' => null,
        'asset_statistics' => null,
        'products' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'valid_time' => 'validTime',
        'value' => 'value',
        'contours' => 'contours',
        'asset_statistics' => 'assetStatistics',
        'products' => 'products'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'valid_time' => 'setValidTime',
        'value' => 'setValue',
        'contours' => 'setContours',
        'asset_statistics' => 'setAssetStatistics',
        'products' => 'setProducts'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'valid_time' => 'getValidTime',
        'value' => 'getValue',
        'contours' => 'getContours',
        'asset_statistics' => 'getAssetStatistics',
        'products' => 'getProducts'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['valid_time'] = isset($data['valid_time']) ? $data['valid_time'] : null;
        $this->container['value'] = isset($data['value']) ? $data['value'] : null;
        $this->container['contours'] = isset($data['contours']) ? $data['contours'] : null;
        $this->container['asset_statistics'] = isset($data['asset_statistics']) ? $data['asset_statistics'] : null;
        $this->container['products'] = isset($data['products']) ? $data['products'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets valid_time
     * @return string
     */
    public function getValidTime()
    {
        return $this->container['valid_time'];
    }

    /**
     * Sets valid_time
     * @param string $valid_time
     * @return $this
     */
    public function setValidTime($valid_time)
    {
        $this->container['valid_time'] = $valid_time;

        return $this;
    }

    /**
     * Gets value
     * @return double
     */
    public function getValue()
    {
        return $this->container['value'];
    }

    /**
     * Sets value
     * @param double $value
     * @return $this
     */
    public function setValue($value)
    {
        $this->container['value'] = $value;

        return $this;
    }

    /**
     * Gets contours
     * @return string
     */
    public function getContours()
    {
        return $this->container['contours'];
    }

    /**
     * Sets contours
     * @param string $contours
     * @return $this
     */
    public function setContours($contours)
    {
        $this->container['contours'] = $contours;

        return $this;
    }

    /**
     * Gets asset_statistics
     * @return \Swagger\Client\Model\DailyAssetSeriesAssetStatistics
     */
    public function getAssetStatistics()
    {
        return $this->container['asset_statistics'];
    }

    /**
     * Sets asset_statistics
     * @param \Swagger\Client\Model\DailyAssetSeriesAssetStatistics $asset_statistics
     * @return $this
     */
    public function setAssetStatistics($asset_statistics)
    {
        $this->container['asset_statistics'] = $asset_statistics;

        return $this;
    }

    /**
     * Gets products
     * @return string[]
     */
    public function getProducts()
    {
        return $this->container['products'];
    }

    /**
     * Sets products
     * @param string[] $products
     * @return $this
     */
    public function setProducts($products)
    {
        $this->container['products'] = $products;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


