<?php
/**
 * HourlyEvapotranspirationShortCropApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SkyWise Insight API (Beta)
 *
 * The SkyWise Insight API is an interface to WDT’s Weather as a Service® analytics platform,  allowing application developers to leverage high quality weather information  for applications, and products. The SkyWise Insight API provides access to  historical, current, and forecast data for any region of interest,  such as an agriculture field, urban area, or utility service area.  API response formats can include time-series, summaries, or contours.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * HourlyEvapotranspirationShortCropApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class HourlyEvapotranspirationShortCropApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for hourlyEvapotranspirationShortCropByAsset
     *
     * Hourly Evapotranspiration Short Crop by asset.
     *
     */
    public function testHourlyEvapotranspirationShortCropByAsset()
    {
    }

    /**
     * Test case for hourlyEvapotranspirationShortCropByLocation
     *
     * Hourly Evapotranspiration Short Crop by location.
     *
     */
    public function testHourlyEvapotranspirationShortCropByLocation()
    {
    }

    /**
     * Test case for hourlyEvapotranspirationShortCropContoursByAsset
     *
     * Hourly Evapotranspiration Short Crop contours by asset.
     *
     */
    public function testHourlyEvapotranspirationShortCropContoursByAsset()
    {
    }
}
